djangobasico/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('favoritos.urls'))

]

favoritos/urls.py
from django.urls import path

from .views import *

app_name = 'favoritos'

urlpatterns = [
    path('', index_favoritos, name='index'),
    path('crear', crear_favoritos, name='crear'),
    path('borrar/<int:pk>', borrar_favoritos,name='borrar'),
    path('detalle/<int:pk>', detalle_favoritos,name='detalle'),
    path('actualizar/<int:pk>', actualizar_favoritos,name='actualizar'),
]

favoritos/models.py
from django.db import models

# Create your models here.

class Favoritos(models.Model):
    nombre =  models.CharField(max_length=50, blank=True)
    url = models.URLField()

favoritos/forms.py
from django import forms
from .models import Favoritos

class FavoritoForm(forms.Form):
    nombre  = forms.CharField()
    url = forms.URLField()

class FavoritoModelForm(forms.ModelForm):
    class Meta:
        model = Favoritos
        fields = '__all__'

favoritos/views.py
from django.shortcuts import render, redirect
from .models import Favoritos
from .forms import FavoritoModelForm

# Create your views here.

def index_favoritos(request):
    favioritos_lista = Favoritos.objects.all()
    
        
    context = {
            'favoritos_lista' : favioritos_lista
        }
   

    return render(request, 'favoritos/lista.html', context)

def crear_favoritos(request):

    form = FavoritoModelForm()

    if request.method == 'POST':
        
        form = FavoritoModelForm(request.POST)
        
        if form.is_valid():
            form.save()
        else:
            print(form.errors)

            
    context = {
            'form':form,
            'titulo':'Crear favorito'
        }
       
    return render(request, 'favoritos/crear.html',context)

def borrar_favoritos(request, pk):
    Favoritos.objects.get(pk=pk).delete()
    return redirect('favoritos:index')

def detalle_favoritos(request, pk):
    favorito = Favoritos.objects.get(pk=pk)

    return render(request,'favoritos/detalle.html', context={'object':favorito})


def actualizar_favoritos(request, pk):
    favorito = Favoritos.objects.get(pk=pk)

    form = FavoritoModelForm(instance=favorito)

    if request.method == 'POST':
        
        form = FavoritoModelForm(request.POST, instance=favorito)
        
        if form.is_valid():
            form.save()
        else:
            print(form.errors)

            
    context = {
            'form':form,
            'titulo':'Actualizar Favorito'
        }
       
    return render(request, 'favoritos/crear.html',context)

favoritos/templates/favoritos/crear.html
{% extends "base_bs530.html" %} {% block main %}

<div class="container">
  <div class="row">
    <di class="col">
      <h1>{{titulo}}</h1>
      <p><a href="{% url 'favoritos:index' %}">Atras</a></p>
      <form method="POST">
        {% csrf_token %}
        <table class="table">
          {{ form.as_table}}
        </table>
        <input type="submit" class="btn btn-outline-primary" />
      </form>
    </di>
  </div>
</div>

{% endblock main %}

favoritos/templates/favoritos/detalle.html
{% extends "base_bs530.html" %} {{% block main %}

<div class="container">
  <div class="row">
    <div class="col">
      <h1>Detalle favorito</h1>
      <p><a href="{% url 'favoritos:index' %}">Atras</a></p>
      <p>{{object.nombre}}</p>
      <p><a href="{{object.url}}">{{object.url}}</a></p>
    </div>
  </div>
</div>

{% endblock main %}}

favoritos/templates/favoritos/lista.html
{% extends "base_bs530.html" %} {% block main %}
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Favoritos</h1>
      <p>
        <a href="{% url 'favoritos:crear' %}" class="btn btn-outline-primary"
          >Nuevo</a
        >
      </p>
    </div>
  </div>
</div>

<div class="row">
  <div class="col">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th>Nombre</th>
          <th>url</th>
        </tr>
      </thead>
      <tbody>
        {% for favorito in favoritos_lista %}
        <tr>
          <td>{{ favorito.nombre }}</td>
          <td>{{ favorito.url }}</td>
          <td>
            <a
              href="{% url 'favoritos:borrar' favorito.pk %}"
              class="btn btn-outline-danger mb-2"
              >Borrar</a
            >
            <br />
            <a
              href="{% url 'favoritos:detalle' favorito.pk %}"
              class="btn btn-outline-info mb-2"
            >
              Detalle</a
            >
            <br />
            <a
              href="{% url 'favoritos:actualizar' favorito.pk %}"
              class="btn btn-outline-primary mb-2"
              >Actualizar</a
            >
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock main %} {% load static %}

templates/base_bs530.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Favoritos</title>
    <link href="{% static 'bs530/css/bootstrap.min.css' %}" rel="stylesheet" />
    {% block extra_css %}{% endblock %}
  </head>
  <body>
    {% block main %}{% endblock %}

    <script src="{% static 'bs530/js/bootstrap.bundle.min.js' %}"></script>
    {% block extra_js %}{% endblock %}
  </body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>favoritos</h1>
  </body>
</html>